### PR TITLE
Current State Node: Preserve original message with options to override topic and payload

### PR DESCRIPTION
**Pull request by declankenny**
Based on the discussion in issue https://github.com/AYapejian/node-red-contrib-home-assistant/issues/15 which was continued in pull request https://github.com/AYapejian/node-red-contrib-home-assistant/pull/34 , this change adds two checkboxes to the UI,  `override_topic` and `override_payload` to the Current State Node, allowing the user to preserve the incoming message topic and payload or override them with the `entity.id` and `status` - replicating the existing behavior.

Both controls default to `selected` to allow the UI form to replicate existing design.

On the back-end, the code will trap for `undefined` values coming from these two controls and default to selected. This ensures backward compatibility for existing nodes.

### CODE REVIEW

**Comment by declankenny** [comment]
@AYapejian Should we be submitting Pull Requests to the `master` or `dev-master` branch? I can close this one and resubmit if required.

**Comment by MosquitoD4K** [comment]
Please merge this, as it is otherwise a pain to do some awesome stuff.

**Comment by AYapejian** [comment]
@declankenny thanks for the PR.  Should be dev-master, not that anyone would know, I need to throw together the contributing file and some other house keeping stuff.  I've been manually changing the target branch for the PRs, so if you don't recreate it its not a big deal.

Trying to get caught up on the project this week and I'll get all the PRs in as well, that is if nothing blows up irl

**Comment by OmgImAlexis** [comment]
@AYapejian is this in the current 0.3.2 release on NPM?

I'm seeing the same results with and without the override boxes checked.

**Comment by Mobyn** [comment]
@OmgImAlexis @AYapejian I can second. Seeing new message from current state node even with those boxes unchecked

**Comment by DelukaDZ** [comment]
Same here

**Comment by rogersmj** [comment]
Same here. New to Node-Red and thought I was loosing my mind until I found this thread :D 

@AYapejian Using 0.3.2 at the moment, it seems to ignore those checkboxes and always overrides the original message. This is causing me to have to design some of my flows very inefficiently.

**Comment by chimpy** [comment]
Huuuuge +1. A fix for the override options would be amazing!

**Comment by chimpy** [comment]
I'm not a JS expert by any means, but when you look at the code here: https://github.com/AYapejian/node-red-contrib-home-assistant/pull/55/commits/4c36223faf94ce4cf183428934c6cbb1a9f2e2dd

The if block just assembles the message in exactly the same way as the removed lines, 50-51. I don't know how, but shouldn't lines 65 and 69 be inserting the previous message's data here?

**Comment by chimpy** [comment]
Fix is here in fact: https://github.com/AYapejian/node-red-contrib-home-assistant/pull/78

**Pull request merged**
